.TH SSCT 1 ssct\-VERSION
.SH NAME
ssct \- set screen color temperature (X11)
.SH SYNOPSIS
.B ssct
.RB [options]
.RB [temperature]
.RB [brightness]

.SH DESCRIPTION
.B ssct
sets the screen's color temperature.

.SH OPTIONS
.TP
.B -v
verbose output.
.TP
.B -d
Shift temperature by temperature value
.TP
.B -s N
Zero-based index of screen to use.
.TP
.B -c N
Zero-based index of CRTC to use.
.TP
.BI [temperature]
Black body temperature
.br
If the value is 0, xsct sets the color temperature to the default of 6500
.br
If no arguments are passed, xsct estimates the current display temperature and brightness
.TP
.BI [brightness]
Linear brightness between 0.0 (inclusive) and 1.0 (inclusive). The default value is 1.0 if no parameter is passed.

.SH AUTHOR
ssct is based on sct by Ted Unangst <tedu@openbsd.org>

.SH SEE ALSO
redshift(1), xtemp(1)
